### ISSUE TITLE
Container fwddp-daemon rootfs read-only access causes problem to nvmupdate64e in container

### ISSUE THREAD

**Issue by jianzzha** [intel/intel-ethernet-operator#11]
In OCP4.12, with image bundle build from the source (commit id ad194376bcd72341b78b1a748500ef0c0071576e) , update ice FW from 4.10 -> 4.20 fails.

It appears that when 4.20 nvmupdate64e does the FW update, it  needs to temporarily write the .BIN file to /lib/firmware. Because inside the container the rootfs is a read-only mounted, the /lib/firmware/<FW.BIN> creation will fail, and this causes the  nvmupdate64e to error out with exit code 6.

To prove this read only rootfs mount indeed is the cause of the issue, I modified the Dockerfile.daemon and use a script (entry.sh) as the entrypoint and it changes the rootfs mount to "RW" before starting the /fwddp_daemon, as illustrated below,
```
# in Dockerfile.daemon
COPY entry.sh /entry.sh
RUN chmod 777 /entry.sh
ENTRYPOINT ["/entry.sh"]

# in entry.sh
#!/bin/sh
echo "changing sysroot to write-read"
mount -o remount,rw /
echo "creating /lib/firmware"
mkdir /lib/firmware
/fwddp_daemon
```

This change does make the FW update success.

**Comment by jianzzha** [comment]
Update: this read only rootfs mount is observed on OCP4.12 with the bundle image built from the latest git tree; on OCP4.11 with the certified 0.1.0 image this is not an issue.

**Comment by rafal-lal** [comment]
Closing due to no new updates. Since release 23.08 updating firmware to 4.2 also works properly with operator built from git tree.
