### ISSUE TITLE
[RFE] IEO to manage OEM branded cards for firmware updates

### ISSUE THREAD

**Issue by novacain1** [intel/intel-ethernet-operator#8]
Presently today IEO only works with Intel branded 800 series NICs:
https://github.com/intel/intel-ethernet-operator/blob/main/docs/intel-ethernet-operator-release-notes.md

However, the partner ecosystem of OEM branded cards remains a gap, which are very important in the context of firmware updates.  Dell, HPe, and other pertinent System Vendor manufacturers have cards that do use the CVL 800 series chipset / die, but are *not* covered by firmware updates today (my understanding) that could be serviced by IEO.  This leaves a gap in coverage to get customer NIC cards to a higher level of firmware in kubernetes environments.

This RFE attempts to identify ways to close this gap.  Could RFE be enhanced to cover known OEM variant 800 series NICs?

**Comment by rafal-lal** [comment]
Sorry for such late response. Unfortunately OEM cards are not supported by tool that Intel Ethernet Operator leverages for firmware updates (NVM Update utility). Some OEM vendors explicitly lock cards for methods other then their official firmware packages (which follows different versioning and release cycle) and we don't have any control over it. Forcing updates may also lead to warranty void.
